name: GitHubAction Demo

on: push

jobs:
  Action:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build Project
        run: ./mvnw clean package
      - name : print intex.html
        run: cat index.html


