name: GitHubAction Demo

on: push

jobs:
  Action:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v4
      - name : print intex.html
        run: cat index.html


