name: My-Workflow

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: build step
        run: echo  "buils by first workflow"

  test:
    runs-on: ubuntu-latest

    steps:
      - name: test Phase
        run: echo "run the test cses"

     
