name: needJob
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: buils step
        run: echo "run this buils job"
  test:
     runs-on: ubuntu-latest
     needs: build

     steps: 
       - name: test step 
         run: echo " run the test job"

  diploye:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: deploye step
        run: echo "run the deploye step"
    
       
 
