name: ScerateWF

on: workflow_dispatch

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: print scrate
        run: echo " hello this is my docker password , ${{ secrets.MY_PASSWORD }} "
